### ISSUE TITLE
Export Character to Blender not generating .fbx file

### ISSUE THREAD

**Issue by jotoss** [soupday/CC4-Blender-Tools-Plugin#2]
First of all thanks a lot for providing these Blender tools.
When using the `Export Character to Blender` plugin menu item I see the Save As file dialog and can specify the filename but no .fbx file is actually written out.
I added some print() debug outputs and the function `RLPy.RFileIO.ExportFbxFile()` is reached and returns with the following result:
`result.GetStatusCode()` => `RLPy.RStatus.Failure`

Test environment:
+ Windows 10
+ CC 4.0.0511.1
  + Actor>Base>Neutral_M
+ CC-Blender-Tools-Plugin: 1.0.8, 1.0.6

**Comment by soupday** [comment]
There's a problem with python API at the moment. Apparently the API for the export function is part of iClone 8 so it only works if iClone 8 is installed.

The RL Devs know about it, it's one the first things I brought up, so it should hopefully be fixed soon.
